enum Role {
  ADMIN
  MEMBER
}

type User {
  email: String!
  salt: String!
  password: String!
  role: Role!
  deleted: Boolean!
  friends: [User!]!
}

type Query {
  users: [User!]!
  user(email: String!): User
}

type Mutation {
  updatePassword(email: String!, rawPassword: String!): User
}
