type User { ... }
enum Role { ... }

type Query {
  users: [User!]!
  user(id: ID!): User
}

type Error {
  code: String!
  message: String!
}

type Mutation {
  updatePassword(userId: ID!, rawPassword: String!): Error
}
